### ISSUE TITLE
事务恢复的疑问

### ISSUE THREAD

**Issue by buguniao** [changmingxie/tcc-transaction#53]
代码里只是根据超时时间来进行事务恢复，如果原来的事务还在进行中，这样会存在问题，如何解决的？

**Comment by changmingxie** [comment]
@buguniao 使用版本号控制，事务超时了，恢复机制将尝试进行事务恢复，恢复时会更新版本号（乐观锁）以获得事务控制权，原来的事务因为失去了控制权，则在更新事务状态时失败，并终止事务继续进行。

**Comment by Fly-Coder** [comment]
我在代码中没有看到changeStatus时候对版本号有控制，麻烦告知下，具体代码是在哪部分

**Comment by mrsWangxing** [comment]
我最近看别人视频讲的 自己也分析了下   仅供参考 我这边日志记录的持久层是数据库
所以你看 JdbcTransactionRepository的doUpdate方法,里面有version的部分.如果用的其他持久层 如果是redis zookeeper 估计里面也有 我没看过

**Comment by Fly-Coder** [comment]
嗯，我也是看源码分析中提到采用乐观锁的方式更新。我查看了源码，在doUpdate中有获取version的代码。同时updateVersion。但是并没有去判断当前Current中的Transaction的version和数据库中的是否一致，这里是我疑惑的地方。

**Comment by mrsWangxing** [comment]
transaction一个发起者多个参与者，每个参与者执行的顺序 以及对应的version在准备阶段都确认了，在状态改为确认中，真正执行的时候每个确认阶段，即使在多实例情况下，只要不是自己的阶段，都会忽略的，我用的版本是1.1的版本，唯一问题就是准备结束了在改为确认中状态没改成功也会回滚任务的这一点不好，其他的感觉都没啥问题，建议你在仔细看看，PS 不知道1.2的和1.1有多大区别，任务部分有没有优化




    
    
        
            
                
                    
                        
                    
                    
                        
                            1435648802
                            
                            
                                
                                    邮箱：1435648802@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年09月16日 18:50，Fly-Coder 写道： 嗯，我也是看源码分析中提到采用乐观锁的方式更新。我查看了源码，在doUpdate中有获取version的代码。同时updateVersion。但是并没有去判断当前Current中的Transaction的version和数据库中的是否一致，这里是我疑惑的地方。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changmingxie/tcc-transaction","title":"changmingxie/tcc-transaction","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/changmingxie/tcc-transaction"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Fly-Coder in #53: \r\n嗯，我也是看源码分析中提到采用乐观锁的方式更新。我查看了源码，在doUpdate中有获取version的代码。同时updateVersion。但是并没有去判断当前Current中的Transaction的version和数据库中的是否一致，这里是我疑惑的地方。"}],"action":{"name":"View Issue","url":"https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421744094"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421744094",
"url": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421744094",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [changmingxie/tcc-transaction] 事务恢复的疑问 (#53)",
"sections": [
{
"text": "",
"activityTitle": "**Fly-Coder**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Fly-Coder",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421744094"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 187863572\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Fly-Coder** [comment]
我现在看的源码是 1.2.x版本的，你说的执行顺序没问题，只是我在源码中没有找到关于version的判断。

**Comment by mrsWangxing** [comment]
有空我去看看1.2的哈 估计都差不多




    
    
        
            
                
                    
                        
                    
                    
                        
                            1435648802
                            
                            
                                
                                    邮箱：1435648802@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年09月16日 19:50，Fly-Coder 写道： 我现在看的源码是 1.2.x版本的，你说的执行顺序没问题，只是我在源码中没有找到关于version的判断。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changmingxie/tcc-transaction","title":"changmingxie/tcc-transaction","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/changmingxie/tcc-transaction"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Fly-Coder in #53: 我现在看的源码是 1.2.x版本的，你说的执行顺序没问题，只是我在源码中没有找到关于version的判断。"}],"action":{"name":"View Issue","url":"https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037",
"url": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [changmingxie/tcc-transaction] 事务恢复的疑问 (#53)",
"sections": [
{
"text": "",
"activityTitle": "**Fly-Coder**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Fly-Coder",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 187863572\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mrsWangxing** [comment]
建议你在那里多大点日志 写个例子跑跑 我觉得可以解决你的疑问




    
    
        
            
                
                    
                        
                    
                    
                        
                            1435648802
                            
                            
                                
                                    邮箱：1435648802@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年09月16日 19:52，mrsWangxing 写道： 
有空我去看看1.2的哈 估计都差不多




    
    
        
            
                
                    
                        
                    
                    
                        
                            1435648802
                            
                            
                                
                                    邮箱：1435648802@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年09月16日 19:50，Fly-Coder 写道： 我现在看的源码是 1.2.x版本的，你说的执行顺序没问题，只是我在源码中没有找到关于version的判断。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/changmingxie/tcc-transaction","title":"changmingxie/tcc-transaction","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/changmingxie/tcc-transaction"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Fly-Coder in #53: 我现在看的源码是 1.2.x版本的，你说的执行顺序没问题，只是我在源码中没有找到关于version的判断。"}],"action":{"name":"View Issue","url":"https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037",
"url": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [changmingxie/tcc-transaction] 事务恢复的疑问 (#53)",
"sections": [
{
"text": "",
"activityTitle": "**Fly-Coder**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Fly-Coder",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"changmingxie/tcc-transaction\",\n\"issueId\": 53\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/changmingxie/tcc-transaction/issues/53#issuecomment-421752037"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 187863572\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Fly-Coder** [comment]
嗯，我再仔细看看

**Comment by mrsWangxing** [comment]
刚才又看了下1.2.X的源码 发现和1.1.X确实有点区别。
在资源准备过程中 和 资源确认、回滚、或者调用调度任务都会走 CachableTransactionRepository的update方法。下面是方法体。
      int result = 0;
        try {
            **result = doUpdate(transaction);**
            if (result > 0) {
                putToCache(transaction);
            } else {
                **throw new OptimisticLockException();**
            }
        } finally {
            if (result <= 0) {
                removeFromCache(transaction);
            }
        }
        return result;

先doUpdate 改状态，就是作者所得乐观锁，改成功了 返回1 正常执行流程，改失败了，会抛出OptimisticLockException异常！！还不明白，再仔细看看。
